**Webscraping Artist Data from Current Billboard Top 100 Artist**

In [75]:
# Importing necessary libraries
# BeautifulSoup for HTML parsing
# requests for HTTP requests
# re for regular expressions
# pandas for data manipulation and analysis
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

Parsing HTML Content from Billboard Top 100 Artist Webpage

In [77]:
# Specifying the URL of the Billboard Artist 100 chart
url = 'https://www.billboard.com/charts/artist-100/'

# Sending an HTTP GET request to the specified URL and store the response
response = requests.get(url)

# Parsing the HTML content of the response using BeautifulSoup
soup = BeautifulSoup(response.text, "lxml")

Scraping Billboard Artist 100 Chart Data and Organizing into a Structured List

In [79]:
# Initializing the list where the data will be stored
data = []

# Iterating through each chart entry in the top 100
for e in soup.find_all(attrs={'class':'o-chart-results-list-row-container'}):
    ranking_span = e.h3.find_previous('span')
    # Adding a while loop to handle cases where "New" or "Re-Entry" labels are present between the artist name and ranking
    while ranking_span.get_text(strip=True) in ['RE-\nENTRY', 'NEW']:
        ranking_span = ranking_span.find_previous('span')
    ranking = int(ranking_span.get_text(strip=True))
    name = e.h3.get_text(strip=True)
    weeks = int(e.h3.find_next('span').find_next('span').find_next('span').get_text(strip=True))

    # Extracting and storing the ranking, artist name, and weeks on chart for each entry
    data.append({
        'Ranking':ranking,
        'Artist Name':name,
        'Weeks on Artist 100 Chart':weeks
    })

# Printing the extracted data
data

[{'Ranking': 1,
  'Artist Name': 'Taylor Swift',
  'Weeks on Artist 100 Chart': 547},
 {'Ranking': 2, 'Artist Name': 'Bad Bunny', 'Weeks on Artist 100 Chart': 330},
 {'Ranking': 3, 'Artist Name': 'SZA', 'Weeks on Artist 100 Chart': 281},
 {'Ranking': 4,
  'Artist Name': 'Kendrick Lamar',
  'Weeks on Artist 100 Chart': 472},
 {'Ranking': 5,
  'Artist Name': 'Morgan Wallen',
  'Weeks on Artist 100 Chart': 306},
 {'Ranking': 6,
  'Artist Name': 'Sabrina Carpenter',
  'Weeks on Artist 100 Chart': 59},
 {'Ranking': 7,
  'Artist Name': 'Billie Eilish',
  'Weeks on Artist 100 Chart': 326},
 {'Ranking': 8, 'Artist Name': 'Bruno Mars', 'Weeks on Artist 100 Chart': 529},
 {'Ranking': 9,
  'Artist Name': 'Chappell Roan',
  'Weeks on Artist 100 Chart': 40},
 {'Ranking': 10,
  'Artist Name': 'Teddy Swims',
  'Weeks on Artist 100 Chart': 71},
 {'Ranking': 11,
  'Artist Name': 'Tyler, The Creator',
  'Weeks on Artist 100 Chart': 187},
 {'Ranking': 12,
  'Artist Name': 'Jelly Roll',
  'Weeks on Artist 100 Chart': 131},
 {'Ranking': 13,
  'Artist Name': 'Gracie Abrams',
  'Weeks on Artist 100 Chart': 32},
 {'Ranking': 14, 'Artist Name': 'Shaboozey', 'Weeks on Artist 100 Chart': 40},
 {'Ranking': 15,
  'Artist Name': 'Zach Bryan',
  'Weeks on Artist 100 Chart': 140},
 {'Ranking': 16,
  'Artist Name': 'Post Malone',
  'Weeks on Artist 100 Chart': 447},
 {'Ranking': 17,
  'Artist Name': 'Heidi Montag',
  'Weeks on Artist 100 Chart': 1},
 {'Ranking': 18,
  'Artist Name': 'Luke Combs',
  'Weeks on Artist 100 Chart': 411},
 {'Ranking': 19, 'Artist Name': 'Lil Baby', 'Weeks on Artist 100 Chart': 331},
 {'Ranking': 20,
  'Artist Name': 'The Weeknd',
  'Weeks on Artist 100 Chart': 497},
 {'Ranking': 21, 'Artist Name': 'Hozier', 'Weeks on Artist 100 Chart': 156},
 {'Ranking': 22,
  'Artist Name': 'Ariana Grande',
  'Weeks on Artist 100 Chart': 476},
 {'Ranking': 23, 'Artist Name': 'Lady Gaga', 'Weeks on Artist 100 Chart': 302},
 {'Ranking': 24,
  'Artist Name': 'Chris Stapleton',
  'Weeks on Artist 100 Chart': 482},
 {'Ranking': 25, 'Artist Name': 'ROSE', 'Weeks on Artist 100 Chart': 14},
 {'Ranking': 26,
  'Artist Name': 'Benson Boone',
  'Weeks on Artist 100 Chart': 52},
 {'Ranking': 27, 'Artist Name': 'GloRilla', 'Weeks on Artist 100 Chart': 52},
 {'Ranking': 28,
  'Artist Name': 'Fleetwood Mac',
  'Weeks on Artist 100 Chart': 302},
 {'Ranking': 29, 'Artist Name': 'Future', 'Weeks on Artist 100 Chart': 374},
 {'Ranking': 30,
  'Artist Name': 'Myles Smith',
  'Weeks on Artist 100 Chart': 32},
 {'Ranking': 31, 'Artist Name': 'Drake', 'Weeks on Artist 100 Chart': 549},
 {'Ranking': 32, 'Artist Name': 'Stray Kids', 'Weeks on Artist 100 Chart': 85},
 {'Ranking': 33, 'Artist Name': 'Noah Kahan', 'Weeks on Artist 100 Chart': 84},
 {'Ranking': 34,
  'Artist Name': 'Kanye West',
  'Weeks on Artist 100 Chart': 304},
 {'Ranking': 35, 'Artist Name': 'Metallica', 'Weeks on Artist 100 Chart': 477},
 {'Ranking': 36,
  'Artist Name': 'Linkin Park',
  'Weeks on Artist 100 Chart': 133},
 {'Ranking': 37, 'Artist Name': 'Eminem', 'Weeks on Artist 100 Chart': 510},
 {'Ranking': 38, 'Artist Name': 'Lola Young', 'Weeks on Artist 100 Chart': 5},
 {'Ranking': 39, 'Artist Name': 'Nirvana', 'Weeks on Artist 100 Chart': 241},
 {'Ranking': 40,
  'Artist Name': 'Bailey Zimmerman',
  'Weeks on Artist 100 Chart': 136},
 {'Ranking': 41,
  'Artist Name': 'Cynthia Erivo',
  'Weeks on Artist 100 Chart': 8},
 {'Ranking': 42,
  'Artist Name': 'Travis Scott',
  'Weeks on Artist 100 Chart': 446},
 {'Ranking': 43, 'Artist Name': 'Coldplay', 'Weeks on Artist 100 Chart': 198},
 {'Ranking': 44,
  'Artist Name': 'Frank Ocean',
  'Weeks on Artist 100 Chart': 71},
 {'Ranking': 45,
  'Artist Name': 'Ed Sheeran',
  'Weeks on Artist 100 Chart': 544},
 {'Ranking': 46,
  'Artist Name': 'Lainey Wilson',
  'Weeks on Artist 100 Chart': 126},
 {'Ranking': 47,
  'Artist Name': 'BigXthaPlug',
  'Weeks on Artist 100 Chart': 36},
 {'Ranking': 48,
  'Artist Name': 'Arctic Monkeys',
  'Weeks on Artist 100 Chart': 75},
 {'Ranking': 49, 'Artist Name': 'Rihanna', 'Weeks on Artist 100 Chart': 333},
 {'Ranking': 50,
  'Artist Name': 'Tate McRae',
  'Weeks on Artist 100 Chart': 119},
 {'Ranking': 51, 'Artist Name': 'Ringo Starr', 'Weeks on Artist 100 Chart': 3},
 {'Ranking': 52,
  'Artist Name': 'Tito Double P',
  'Weeks on Artist 100 Chart': 11},
 {'Ranking': 53,
  'Artist Name': 'Michael Jackson',
  'Weeks on Artist 100 Chart': 461},
 {'Ranking': 54, 'Artist Name': 'Charli xcx', 'Weeks on Artist 100 Chart': 69},
 {'Ranking': 55, 'Artist Name': 'Zach Top', 'Weeks on Artist 100 Chart': 13},
 {'Ranking': 56,
  'Artist Name': 'Don Toliver',
  'Weeks on Artist 100 Chart': 27},
 {'Ranking': 57, 'Artist Name': 'Radiohead', 'Weeks on Artist 100 Chart': 36},
 {'Ranking': 58, 'Artist Name': 'Dua Lipa', 'Weeks on Artist 100 Chart': 346},
 {'Ranking': 59,
  'Artist Name': 'Chris Brown',
  'Weeks on Artist 100 Chart': 470},
 {'Ranking': 60, 'Artist Name': 'Doechii', 'Weeks on Artist 100 Chart': 10},
 {'Ranking': 61,
  'Artist Name': 'Miley Cyrus',
  'Weeks on Artist 100 Chart': 216},
 {'Ranking': 62, 'Artist Name': 'J. Cole', 'Weeks on Artist 100 Chart': 416},
 {'Ranking': 63, 'Artist Name': 'GELO', 'Weeks on Artist 100 Chart': 2},
 {'Ranking': 64,
  'Artist Name': 'The Beatles',
  'Weeks on Artist 100 Chart': 340},
 {'Ranking': 65,
  'Artist Name': 'Riley Green',
  'Weeks on Artist 100 Chart': 21},
 {'Ranking': 66, 'Artist Name': 'Mac Miller', 'Weeks on Artist 100 Chart': 82},
 {'Ranking': 67, 'Artist Name': 'Tremonti', 'Weeks on Artist 100 Chart': 4},
 {'Ranking': 68,
  'Artist Name': 'Playboi Carti',
  'Weeks on Artist 100 Chart': 39},
 {'Ranking': 69, 'Artist Name': 'Jimin', 'Weeks on Artist 100 Chart': 33},
 {'Ranking': 70,
  'Artist Name': 'Tucker Wetmore',
  'Weeks on Artist 100 Chart': 39},
 {'Ranking': 71,
  'Artist Name': 'Lana Del Rey',
  'Weeks on Artist 100 Chart': 229},
 {'Ranking': 72, 'Artist Name': 'The Marias', 'Weeks on Artist 100 Chart': 5},
 {'Ranking': 73, 'Artist Name': 'Deftones', 'Weeks on Artist 100 Chart': 34},
 {'Ranking': 74,
  'Artist Name': 'Jordan Davis',
  'Weeks on Artist 100 Chart': 151},
 {'Ranking': 75, 'Artist Name': 'Sexyy Red', 'Weeks on Artist 100 Chart': 42},
 {'Ranking': 76, 'Artist Name': 'Gigi Perez', 'Weeks on Artist 100 Chart': 9},
 {'Ranking': 77, 'Artist Name': 'Gunna', 'Weeks on Artist 100 Chart': 197},
 {'Ranking': 78,
  'Artist Name': 'Megan Moroney',
  'Weeks on Artist 100 Chart': 29},
 {'Ranking': 79,
  'Artist Name': 'Jack Harlow',
  'Weeks on Artist 100 Chart': 183},
 {'Ranking': 80,
  'Artist Name': 'Juice WRLD',
  'Weeks on Artist 100 Chart': 258},
 {'Ranking': 81,
  'Artist Name': 'Tommy Richman',
  'Weeks on Artist 100 Chart': 37},
 {'Ranking': 82,
  'Artist Name': 'Ella Langley',
  'Weeks on Artist 100 Chart': 19},
 {'Ranking': 83, 'Artist Name': 'Neton Vega', 'Weeks on Artist 100 Chart': 3},
 {'Ranking': 84, 'Artist Name': 'Rod Wave', 'Weeks on Artist 100 Chart': 138},
 {'Ranking': 85,
  'Artist Name': 'Creedence Clearwater Revival',
  'Weeks on Artist 100 Chart': 203},
 {'Ranking': 86, 'Artist Name': 'Adele', 'Weeks on Artist 100 Chart': 396},
 {'Ranking': 87,
  'Artist Name': 'Brandon Lake',
  'Weeks on Artist 100 Chart': 7},
 {'Ranking': 88,
  'Artist Name': 'Olivia Rodrigo',
  'Weeks on Artist 100 Chart': 192},
 {'Ranking': 89,
  'Artist Name': 'PARTYNEXTDOOR',
  'Weeks on Artist 100 Chart': 15},
 {'Ranking': 90,
  'Artist Name': 'Dylan Scott',
  'Weeks on Artist 100 Chart': 20},
 {'Ranking': 91,
  'Artist Name': 'Cody Johnson',
  'Weeks on Artist 100 Chart': 133},
 {'Ranking': 92, 'Artist Name': 'Bob Dylan', 'Weeks on Artist 100 Chart': 20},
 {'Ranking': 93,
  'Artist Name': 'Summer Walker',
  'Weeks on Artist 100 Chart': 58},
 {'Ranking': 94,
  'Artist Name': 'Jessie Murph',
  'Weeks on Artist 100 Chart': 13},
 {'Ranking': 95,
  'Artist Name': 'Harry Styles',
  'Weeks on Artist 100 Chart': 275},
 {'Ranking': 96,
  'Artist Name': 'Blake Shelton',
  'Weeks on Artist 100 Chart': 353},
 {'Ranking': 97, 'Artist Name': 'Journey', 'Weeks on Artist 100 Chart': 125},
 {'Ranking': 98,
  'Artist Name': 'Melanie Martinez',
  'Weeks on Artist 100 Chart': 81},
 {'Ranking': 99, 'Artist Name': 'Alex Warren', 'Weeks on Artist 100 Chart': 4},
 {'Ranking': 100, 'Artist Name': 'Doja Cat', 'Weeks on Artist 100 Chart': 253}]

Transforming the list into a dataframe

In [81]:
df = pd.DataFrame(data)
df

    Ranking       Artist Name  Weeks on Artist 100 Chart
0         1      Taylor Swift                        547
1         2         Bad Bunny                        330
2         3               SZA                        281
3         4    Kendrick Lamar                        472
4         5     Morgan Wallen                        306
..      ...               ...                        ...
95       96     Blake Shelton                        353
96       97           Journey                        125
97       98  Melanie Martinez                         81
98       99       Alex Warren                          4
99      100          Doja Cat                        253

[100 rows x 3 columns]

Converting the data table into a csv file

In [83]:
df.to_csv('top100_artists_billboard.csv',index=False)